services:
  db:
    image: postgres:17-alpine
    container_name: credit_db
    environment:
      - POSTGRES_DB=credit_db
      - POSTGRES_USER=credit_user
      - POSTGRES_PASSWORD=credit_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U credit_user -d credit_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: credit_web
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --config gunicorn.conf.py credit_approval_system.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://credit_user:credit_password@db:5432/credit_db
      - DEBUG=1
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
